### ISSUE TITLE
Issue in ReversingIsEzeeee writeup

### ISSUE THREAD

**Issue by Rinnnt** [HackDagos/writeups#1]
The writeup explains that the string found from examine.pyc:
`5669736877614354467b31355f70797468306e5f7468335f623335745f6c346e67753467333f3f7d`
is base64 encoded.
However this is actually hex-encoded ascii codes.

**Comment by HackDagos** [comment]
Our bad, a member of our team was in a hurry to finish all writeups and made a mistake. We're sorry we just updated the solution
